config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def create 
    @flat = Flat.new(flat_params)
    if @flat.after_save
      redirect_to flats_path
    else
      render :new
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :price_per_night, :number_of_guests, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
  <h2>All our Flats(<%= @flats.count %>)</h2>

  <div class="flexbox">
    <% @flats.each do |flat| %>
      <div class="card">
        <img src="https://unsplash.com/photos/kdwahpWYfQo" alt="">
        <div class="basic-info">
          <h3><%= flat.name %></h3>
          <p><%= flat.address %></p>
          <p> <i class="fas fa-users"></i> <%= flat.number_of_guests %> 
          <i class="fas fa-euro-sign"></i> <%= flat.price_per_night %></p>
        </div>
        <div class="links">
          <%= link_to 'More info', flat_path(flat) %>
          <%= link_to  %>
        </div>
        
      </div>
    <% end %>
  </div>
  
</div>

app/views/flats/new.html.erb
<div class="container">
  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.select :number_of_guests, number_of_guests: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16] %>
    <%= f.submit class:'btn btn-primary' %>
  <% end %>

  <p><%= link_to 'back to results', flats_path %></p>
</div>

app/views/flats/show.html.erb
<div class="container">
  <div class="card">
    <h2><%= @flat.name %></h2>
    <p><%= @flat.address %></p>
  </div>

  <div class="card">
    <h3>A bit more about this flat...</h3>
    <p><%= @flat.description %></p>
  </div>
  
  <div class="card">
    <h3>Details</h3>
    <p> <i class="fas fa-users"></i> <%= @flat.number_of_guests %> 
    <i class="fas fa-euro-sign"></i> <%= @flat.price_per_night %></p>
  </div>

  <div class="card">
  <h3>Book this place</h3>
  
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar">
       <h4><%= link_to 'Simple Airbnb', flats_path %></h4>
      <button class="btn"><%= link_to 'add new Flat', new_flat_path %></button>    
    </div>
    <%= yield %>
  </body>
</html>